import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, BookOpen, CalendarDays, ChartNoAxesColumn, Check, ChevronDown, ChevronLeft, ChevronRight, ClipboardCheck, FileText, FolderOpen, LayoutDashboard, LogOut, Menu, Plus, Search, Settings, Users, X } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://146.190.138.248:2000';
const menu = [
  { label: 'Visão geral', icon: LayoutDashboard, path: 'inicio' },
  { label: 'Cadastros', icon: FolderOpen, children: [{ label: 'Turmas', path: 'turmas' }, { label: 'Professores', path: 'professores' }] },
  { label: 'Operacional', icon: ClipboardCheck, children: [{ label: 'Chamadas', path: 'chamadas' }] },
  { label: 'Relatórios', icon: ChartNoAxesColumn, children: [{ label: 'Visão geral', path: 'relatorios' }, { label: 'Frequência', path: 'frequencia' }] },
];
const today = () => new Date().toISOString().slice(0, 10);
const formatDate = (value) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(`${value.slice(0, 10)}T12:00:00Z`)) : '—';

function TechText({ text = 'React Bits', fontSize = 150, fontWeight = 600, color = '#ffffff', accentColor = '#ffffff', reveal = 'letter', dashLength = 4, dashGap = 2, specks = 15 }) {
  const root = useRef(null);
  const canvas = useRef(null);
  useEffect(() => {
    const el = root.current, cv = canvas.current, ctx = cv?.getContext('2d');
    if (!el || !cv || !ctx) return;
    let pointer = { x: 0, y: 0, active: false }, frame = 0, bounds = [];
    const layout = () => {
      const r = el.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2);
      const pixelWidth = Math.max(1, Math.round(r.width * dpr)), pixelHeight = Math.max(1, Math.round(r.height * dpr));
      if (cv.width !== pixelWidth || cv.height !== pixelHeight) { cv.width = pixelWidth; cv.height = pixelHeight; }
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      let size = Math.min(fontSize, r.height * .72, r.width / (text.length * .62));
      ctx.font = `${fontWeight} ${size}px Inter, ui-sans-serif, system-ui, sans-serif`;
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      const width = ctx.measureText(text).width, start = (r.width - width) / 2;
      bounds = [...text].map((letter, i) => ({ letter, x: start + ctx.measureText(text.slice(0, i)).width + ctx.measureText(letter).width / 2, width: ctx.measureText(letter).width }));
      return { r, size };
    };
    const draw = () => {
      const { r, size } = layout(); ctx.clearRect(0, 0, r.width, r.height);
      ctx.font = `${fontWeight} ${size}px Inter, ui-sans-serif, system-ui, sans-serif`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      bounds.forEach((g) => {
        const active = pointer.active && Math.abs(pointer.x - g.x) < Math.max(24, g.width / 2 + 12) && Math.abs(pointer.y - r.height / 2) < 100;
        ctx.save(); ctx.lineWidth = 1.35;
        if (active && reveal !== 'off') { ctx.strokeStyle = color; ctx.setLineDash([dashLength, dashGap]); ctx.strokeText(g.letter, g.x, r.height / 2); }
        else { ctx.fillStyle = color; ctx.fillText(g.letter, g.x, r.height / 2); }
        ctx.restore();
        if (active && specks) { for (let i = 0; i < Math.min(specks, 8); i++) { ctx.fillStyle = accentColor; ctx.globalAlpha = Math.random() * .75; ctx.fillRect(g.x + (Math.random() - .5) * 52, r.height / 2 + (Math.random() - .5) * 62, 2, 2); } ctx.globalAlpha = 1; }
      });
      if (pointer.active) frame = requestAnimationFrame(draw);
    };
    const move = (event) => { const r = el.getBoundingClientRect(); pointer = { x: event.clientX - r.left, y: event.clientY - r.top, active: true }; cancelAnimationFrame(frame); frame = requestAnimationFrame(draw); };
    const leave = () => { pointer.active = false; cancelAnimationFrame(frame); draw(); };
    const observer = new ResizeObserver(draw); observer.observe(el); el.addEventListener('pointermove', move); el.addEventListener('pointerleave', leave); draw();
    return () => { observer.disconnect(); el.removeEventListener('pointermove', move); el.removeEventListener('pointerleave', leave); cancelAnimationFrame(frame); };
  }, [text, fontSize, fontWeight, color, accentColor, reveal, dashLength, dashGap, specks]);
  return <div ref={root} className="tech-text" role="img" aria-label={text}><canvas ref={canvas} /></div>;
}

function App() {
  const [page, setPage] = useState(() => window.location.pathname.split('/').filter(Boolean)[0] || 'inicio'), [expanded, setExpanded] = useState(true), [mobileMenu, setMobileMenu] = useState(false), [search, setSearch] = useState(''), [account, setAccount] = useState(false);
  const [token, setToken] = useState(() => sessionStorage.getItem('chamada-token') || ''), [loginStep, setLoginStep] = useState('login'), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [verifyCode, setVerifyCode] = useState(''), [challenge, setChallenge] = useState(''), [loginMessage, setLoginMessage] = useState(''), [loginBusy, setLoginBusy] = useState(false);
  const [data, setData] = useState({ classes: [], students: [], teachers: [], attendanceRecords: [], discipleshipLessons: [] });
  const [error, setError] = useState('');
  const [className, setClassName] = useState(''), [teacherName, setTeacherName] = useState(''), [teacherPhone, setTeacherPhone] = useState('');
  const [studentName, setStudentName] = useState(''), [studentClass, setStudentClass] = useState('');
  const [selectedClass, setSelectedClass] = useState(''), [selectedTeacher, setSelectedTeacher] = useState(''), [lessonName, setLessonName] = useState(''), [attendanceDate, setAttendanceDate] = useState(today()), [entries, setEntries] = useState({});
  const [frequencyClass, setFrequencyClass] = useState('all');
  const apiFetch = (path, options = {}) => fetch(`${API}${path}`, { ...options, headers: { Accept: 'application/json', ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  const load = async () => { if (!token) return; try { const r = await apiFetch('/school/state'); if (r.status === 401) { sessionStorage.removeItem('chamada-token'); setToken(''); throw new Error('Sua sessão expirou. Entre novamente.'); } if (!r.ok) throw new Error('Não foi possível conectar à API.'); const payload = await r.json(); setData({ classes: payload.classes || [], students: payload.students || [], teachers: payload.teachers || [], attendanceRecords: payload.attendanceRecords || [], discipleshipLessons: payload.discipleshipLessons || [] }); setError(''); } catch (e) { setError(e.message || 'API indisponível. Configure VITE_API_BASE_URL.'); } };
  useEffect(() => { if (token) load(); }, [token]);
  useEffect(() => { const sync = () => setPage(window.location.pathname.split('/').filter(Boolean)[0] || 'inicio'); window.addEventListener('popstate', sync); return () => window.removeEventListener('popstate', sync); }, []);
  useEffect(() => { if (!selectedClass && data.classes.length) setSelectedClass(data.classes[0].id); }, [data.classes, selectedClass]);
  const activeTitle = useMemo(() => menu.flatMap((group) => [group, ...(group.children || [])]).find((item) => item.path === page)?.label || 'Visão geral', [page]);
  const request = async (path, method, body) => { const r = await apiFetch(path, { method, ...(body ? { body: JSON.stringify(body) } : {}) }); const payload = await r.json(); if (!r.ok) throw new Error(payload.message || 'Não foi possível concluir a operação.'); setData({ classes: payload.classes || [], students: payload.students || [], teachers: payload.teachers || [], attendanceRecords: payload.attendanceRecords || [], discipleshipLessons: payload.discipleshipLessons || data.discipleshipLessons }); return payload; };
  const notify = async (fn) => { try { setError(''); await fn(); } catch (e) { setError(e.message || 'Ocorreu um erro.'); } };
  const pageTitles = { inicio: ['Visão geral', 'Acompanhe a atividade da campanha em um só lugar.'], turmas: ['Turmas', 'Crie turmas e organize os participantes da campanha.'], professores: ['Professores', 'Cadastre a equipe e os responsáveis por cada encontro.'], chamadas: ['Chamadas', 'Registre e consulte a participação nos encontros.'], relatorios: ['Relatórios', 'Indicadores gerais para acompanhamento da campanha.'], frequencia: ['Frequência', 'Consulte a frequência por turma e período.'] };
  const [title, subtitle] = pageTitles[page] || pageTitles.inicio;
  const nav = (path) => { setPage(path); setMobileMenu(false); window.history.pushState({}, '', `/${path === 'inicio' ? '' : path}`); };
  const submitLogin = async (event) => { event.preventDefault(); setLoginBusy(true); setLoginMessage(''); try { const path = loginStep === 'login' ? '/auth/login' : '/auth/verify'; const body = loginStep === 'login' ? { email, password } : { challenge, code: verifyCode }; const response = await fetch(`${API}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || 'Não foi possível acessar.'); if (loginStep === 'login') { setChallenge(result.challenge); setLoginStep('verify'); setLoginMessage('Enviamos um código de verificação para seu e-mail.'); } else { sessionStorage.setItem('chamada-token', result.token); setToken(result.token); } } catch (e) { setLoginMessage(e.message || 'Falha de conexão com o servidor.'); } finally { setLoginBusy(false); } };
  if (!token) return <div className="login-page"><section className="login-card"><div className="login-art"><div className="login-brand"><span className="brand-icon"><BookOpen size={21}/></span>CAMPANHA EVANGELIZADORA</div><div className="login-art-copy"><h1>Caminhamos juntos.</h1><p>Cada encontro é uma oportunidade de compartilhar esperança e cuidar uns dos outros.</p></div><span className="login-art-footer">UM SÓ PROPÓSITO, MUITAS VIDAS ALCANÇADAS</span></div><form className="login-form" onSubmit={submitLogin}><span className="eyebrow">ÁREA ADMINISTRATIVA</span><h2>{loginStep === 'login' ? 'Bem-vindo de volta' : 'Confirme seu acesso'}</h2><p>{loginStep === 'login' ? 'Acesse o painel da campanha evangelizadora.' : `Digite o código enviado para ${email}.`}</p>{loginStep === 'login' ? <><label className="field">E-mail<input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="seu@email.com"/></label><label className="field">Senha<input type="password" autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Digite sua senha"/></label></> : <label className="field">Código de verificação<input inputMode="numeric" maxLength={6} required value={verifyCode} onChange={(e) => setVerifyCode(e.target.value)} placeholder="000000"/></label>}{loginMessage && <div className={`login-message ${loginMessage.startsWith('Enviamos') ? 'success' : ''}`}>{loginMessage}</div>}<button className="button primary login-submit" disabled={loginBusy}>{loginBusy ? 'Aguarde…' : loginStep === 'login' ? 'Entrar' : 'Confirmar código'}<ChevronRight size={17}/></button>{loginStep === 'verify' && <button type="button" className="text-button login-back" onClick={() => { setLoginStep('login'); setLoginMessage(''); }}>Voltar para o login</button>}<div className="login-footnote">Acesse para continuar sua jornada.</div></form></section></div>;
  const createClass = () => notify(async () => { if (!className.trim()) return; await request('/school/classes', 'POST', { name: className.trim(), description: '' }); setClassName(''); });
  const createStudent = () => notify(async () => { if (!studentName.trim()) return; await request('/school/students', 'POST', { name: studentName.trim(), birthDate: '', studentPhone: '', email: '', guardianName: '', guardianPhone: '', address: '', notes: '', classIds: studentClass ? [studentClass] : [] }); setStudentName(''); });
  const createTeacher = () => notify(async () => { if (!teacherName.trim()) return; await request('/school/teachers', 'POST', { name: teacherName.trim(), phone: teacherPhone.replace(/\D/g, '') }); setTeacherName(''); setTeacherPhone(''); });
  const saveAttendance = () => notify(async () => { const classGroup = data.classes.find((item) => item.id === selectedClass); if (!classGroup || !selectedTeacher) return setError('Selecione uma turma e um professor.'); const students = classGroup.studentIds.map((id) => data.students.find((student) => student.id === id)).filter(Boolean); await request('/school/attendance', 'POST', { classId: selectedClass, lessonName: lessonName || data.discipleshipLessons[0] || 'Encontro evangelizador', teacherIds: [selectedTeacher], date: attendanceDate, notes: '', entries: students.map((student) => ({ studentId: student.id, status: entries[student.id] || 'present', note: '' })) }); setEntries({}); });
  const stats = [{ label: 'Turmas', value: data.classes.length, icon: Users, color: 'blue' }, { label: 'Participantes', value: data.students.length, icon: Users, color: 'cyan' }, { label: 'Professores', value: data.teachers.length, icon: BookOpen, color: 'green' }, { label: 'Encontros registrados', value: data.attendanceRecords.length, icon: Check, color: 'amber' }];
  const records = [...data.attendanceRecords].reverse();

  return <div className="app-shell">
    <header className="topbar"><div className="brandline"><button className="icon-button mobile-only" onClick={() => setMobileMenu(!mobileMenu)} aria-label="Abrir menu"><Menu size={21}/></button><button className="brand" onClick={() => nav('inicio')}><span className="brand-icon"><BookOpen size={21}/></span><span>CAMPANHA EVANGELIZADORA</span></button></div><div className="account-area"><span className="account-email">Painel de gestão</span><button className="account-trigger" onClick={() => setAccount(!account)}><span className="avatar">CE</span><span>Administrador</span><ChevronDown size={16}/></button>{account && <div className="account-menu"><strong>Campanha Evangelizadora</strong><button onClick={() => setAccount(false)}><Settings size={15}/> Configurações</button><button onClick={() => { sessionStorage.removeItem('chamada-token'); setToken(''); setAccount(false); }}><LogOut size={15}/> Sair</button></div>}</div></header>
    <div className="body-layout">{(expanded || mobileMenu) && <><div className={`backdrop ${mobileMenu ? 'show' : ''}`} onClick={() => setMobileMenu(false)}/><aside className={`sidebar ${mobileMenu ? 'sidebar-mobile-open' : ''}`}><div className="side-heading"><span>NAVEGAÇÃO</span><button className="icon-button" onClick={() => setExpanded(!expanded)} aria-label="Recolher menu"><ChevronLeft size={18}/></button></div><label className="searchbox"><Search size={16}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar no menu"/><kbd>/</kbd></label><nav>{menu.map((group) => { const Icon = group.icon; const children = group.children?.filter((child) => child.label.toLowerCase().includes(search.toLowerCase())); if (group.path) return (!search || group.label.toLowerCase().includes(search.toLowerCase())) && <button key={group.path} className={`nav-link ${page === group.path ? 'active' : ''}`} onClick={() => nav(group.path)}><Icon size={18}/><span>{group.label}</span></button>; return children?.length > 0 && <div className="nav-group" key={group.label}><div className="nav-group-title"><Icon size={17}/><span>{group.label}</span></div>{children.map((child) => <button key={child.path} className={`nav-link sub-link ${page === child.path ? 'active' : ''}`} onClick={() => nav(child.path)}>{child.label}</button>)}</div>; })}</nav><div className="sidebar-bottom"><div className="help-badge"> <span>?</span><div><b>Precisa de ajuda?</b><small>Acesse os relatórios da campanha</small></div></div></div></aside></>}
      <main className="main-column"><div className="breadcrumb"><button onClick={() => nav('inicio')}>Início</button><span>/</span><strong>{activeTitle}</strong><button className="collapse-menu" onClick={() => setExpanded(!expanded)}><Menu size={17}/></button></div><div className="page-content"><div className="page-heading"><div><div className="eyebrow">CAMPANHA EVANGELIZADORA</div><h1>{title}</h1><p>{subtitle}</p></div><span className="today-pill"><CalendarDays size={15}/>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long' }).format(new Date())}</span></div>
        {error && <div className="alert"><Activity size={17}/><span>{error}</span><button onClick={load}>Tentar novamente</button><button className="alert-close" onClick={() => setError('')}><X size={16}/></button></div>}
        {page === 'inicio' && <><section className="welcome-card"><div className="welcome-copy"><span className="welcome-label">PAINEL DE EVANGELIZAÇÃO</span><div className="tech-wrap"><TechText text="Campanha Evangelizadora" fontSize={58} fontWeight={650} color="#ffffff" accentColor="#b7d9ff" reveal="letter" dashLength={3} dashGap={2} specks={12}/></div><p>Um só propósito, muitas vidas alcançadas. Acompanhe os encontros e cuide de cada pessoa.</p><div className="welcome-date"><CalendarDays size={15}/>{new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date())}</div></div><div className="welcome-symbol"><BookOpen size={35}/></div><div className="welcome-decoration"/></section><section className="section-block"><div className="section-heading"><div><h2>Resumo da campanha</h2><p>Indicadores atualizados com seus cadastros e encontros.</p></div><button className="text-button" onClick={() => nav('relatorios')}>Ver relatórios <ChevronRight size={16}/></button></div><div className="stats-grid">{stats.map(({ label, value, icon: Icon, color }) => <article className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={`stat-icon ${color}`}><Icon size={18}/></span></div><strong>{value}</strong><small>no sistema</small></article>)}</div></section><div className="quick-actions"><button className="button primary" onClick={() => nav('chamadas')}><Plus size={17}/> Registrar encontro <ChevronRight size={16}/></button><button className="button secondary" onClick={() => nav('turmas')}><Users size={17}/> Gerenciar turmas</button></div><section className="panel"><div className="panel-heading"><div><h2>Atividade recente</h2><p>Últimos encontros registrados na campanha.</p></div><button className="icon-button muted" onClick={load} title="Atualizar"><Activity size={17}/></button></div>{records.length ? <div className="record-list">{records.slice(0, 5).map((record) => <div className="record-row" key={record.id}><span className="record-symbol"><ClipboardCheck size={18}/></span><div className="record-info"><b>{data.classes.find((c) => c.id === record.classId)?.name || 'Encontro evangelizador'}</b><span>{record.lessonName || 'Encontro'} · {formatDate(record.date)}</span></div><span className="badge green">{record.entries?.filter((e) => e.status === 'present').length || 0} presentes</span></div>)}</div> : <div className="empty-state"><span className="empty-icon"><FileText size={20}/></span><b>Nenhum encontro registrado ainda</b><p>Registre o primeiro encontro para ver a atividade recente aqui.</p><button className="button secondary" onClick={() => nav('chamadas')}>Registrar encontro <ChevronRight size={15}/></button></div>}</section></>}
        {page === 'turmas' && <><section className="panel"><PanelHeading icon={Users} title="Nova turma" description="Organize participantes por grupo ou local de encontro."/><form className="form-row" onSubmit={(e) => { e.preventDefault(); createClass(); }}><label className="field grow">Nome da turma<input value={className} onChange={(e) => setClassName(e.target.value)} placeholder="Ex.: Grupo Esperança" required/></label><button className="button primary form-button"><Plus size={16}/> Criar turma</button></form></section><section className="panel"><PanelHeading icon={FolderOpen} title="Turmas cadastradas" description={`${data.classes.length} grupos cadastrados`}/>{data.classes.length ? <div className="table-wrap"><table><thead><tr><th>Nome da turma</th><th>Descrição</th><th>Participantes</th><th></th></tr></thead><tbody>{data.classes.map((group) => <tr key={group.id}><td><b>{group.name}</b></td><td>{group.description || '—'}</td><td><span className="badge blue">{group.studentIds?.length || 0} pessoas</span></td><td><button className="small-danger" onClick={() => window.confirm(`Apagar a turma ${group.name}?`) && notify(() => request(`/school/classes/${group.id}`, 'DELETE'))}>Apagar</button></td></tr>)}</tbody></table></div> : <Empty message="Nenhuma turma cadastrada" detail="Crie uma turma para organizar os participantes."/>}</section></>}
        {page === 'turmas' && <section className="panel"><PanelHeading icon={Users} title="Novo participante" description="Cadastre uma pessoa e, se quiser, vincule-a a uma turma."/><form className="form-row" onSubmit={(e) => { e.preventDefault(); createStudent(); }}><label className="field grow">Nome completo<input value={studentName} onChange={(e) => setStudentName(e.target.value)} placeholder="Ex.: Maria Oliveira" required/></label><label className="field grow">Turma<select value={studentClass} onChange={(e) => setStudentClass(e.target.value)}><option value="">Sem turma por enquanto</option>{data.classes.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label><button className="button primary form-button"><Plus size={16}/> Cadastrar participante</button></form>{data.students.length > 0 && <div className="table-wrap student-table"><table><thead><tr><th>Participante</th><th>Turma</th></tr></thead><tbody>{data.students.map((student) => <tr key={student.id}><td><b>{student.name}</b></td><td>{data.classes.filter((group) => group.studentIds?.includes(student.id)).map((group) => group.name).join(', ') || 'Sem turma'}</td></tr>)}</tbody></table></div>}</section>}
        {page === 'professores' && <><section className="panel"><PanelHeading icon={BookOpen} title="Novo professor" description="Cadastre os responsáveis pelos encontros."/><form className="form-row" onSubmit={(e) => { e.preventDefault(); createTeacher(); }}><label className="field grow">Nome completo<input value={teacherName} onChange={(e) => setTeacherName(e.target.value)} placeholder="Ex.: Ana Souza" required/></label><label className="field grow">Telefone (opcional)<input value={teacherPhone} onChange={(e) => setTeacherPhone(e.target.value)} placeholder="(11) 99999-9999"/></label><button className="button primary form-button"><Plus size={16}/> Cadastrar</button></form></section><section className="panel"><PanelHeading icon={Users} title="Equipe" description="Pessoas disponíveis para conduzir os encontros."/>{data.teachers.length ? <div className="people-list">{data.teachers.map((teacher) => <div className="person-row" key={teacher.id}><span className="person-avatar">{teacher.name.split(' ').map((n) => n[0]).slice(0, 2).join('').toUpperCase()}</span><div className="person-info"><b>{teacher.name}</b><span>{teacher.phone || 'Sem telefone informado'}</span></div><span className="badge green">Ativo</span><button className="small-danger" onClick={() => window.confirm(`Apagar ${teacher.name}?`) && notify(() => request(`/school/teachers/${teacher.id}`, 'DELETE'))}>Apagar</button></div>)}</div> : <Empty message="Nenhum professor cadastrado" detail="Cadastre a equipe para registrar os encontros."/>}</section></>}
        {page === 'chamadas' && <><section className="panel"><PanelHeading icon={ClipboardCheck} title="Registrar encontro" description="Selecione o grupo e marque a participação de cada pessoa."/><div className="form-grid"><label className="field">Turma<select value={selectedClass} onChange={(e) => setSelectedClass(e.target.value)}><option value="">Selecione uma turma</option>{data.classes.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field">Responsável<select value={selectedTeacher} onChange={(e) => setSelectedTeacher(e.target.value)}><option value="">Selecione um professor</option>{data.teachers.map((t) => <option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label className="field">Tema do encontro<select value={lessonName} onChange={(e) => setLessonName(e.target.value)}><option value="">Encontro evangelizador</option>{data.discipleshipLessons.map((lesson) => <option key={lesson}>{lesson}</option>)}</select></label><label className="field">Data<input type="date" value={attendanceDate} onChange={(e) => setAttendanceDate(e.target.value)}/></label></div>{selectedClass && <div className="attendance-list"><h3>Participantes do grupo</h3>{data.classes.find((c) => c.id === selectedClass)?.studentIds?.map((id) => data.students.find((s) => s.id === id)).filter(Boolean).map((student) => <div className="attendance-person" key={student.id}><span>{student.name}</span><div className="status-options">{[['present','Presente'],['absent','Ausente'],['justified','Justificada'],['late','Atrasado']].map(([status, label]) => <button key={status} onClick={() => setEntries({ ...entries, [student.id]: status })} className={`status-choice ${((entries[student.id] || 'present') === status) ? `selected ${status}` : ''}`}>{label}</button>)}</div></div>)}</div>}<div className="form-footer"><button className="button primary" onClick={saveAttendance}><Check size={16}/> Salvar encontro</button></div></section><section className="panel"><PanelHeading icon={CalendarDays} title="Histórico recente" description="Encontros registrados por data."/>{records.length ? <div className="record-list">{records.map((record) => <div className="record-row" key={record.id}><span className="record-symbol"><CalendarDays size={18}/></span><div className="record-info"><b>{data.classes.find((c) => c.id === record.classId)?.name || 'Turma removida'}</b><span>{record.lessonName || 'Encontro'} · {formatDate(record.date)}</span></div><span className="badge green">{record.entries?.filter((e) => e.status === 'present').length || 0} presentes</span></div>)}</div> : <Empty message="Nenhum encontro registrado" detail="Os encontros salvos aparecerão aqui."/>}</section></>}
        {page === 'relatorios' && <section className="panel"><PanelHeading icon={ChartNoAxesColumn} title="Resumo da campanha" description="Indicadores gerais para acompanhamento."/><div className="stats-grid report-stats">{stats.map(({ label, value, icon: Icon, color }) => <article className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={`stat-icon ${color}`}><Icon size={18}/></span></div><strong>{value}</strong><small>atualizado agora</small></article>)}</div><div className="report-links"><button className="button secondary" onClick={() => nav('frequencia')}>Consultar frequência <ChevronRight size={16}/></button><button className="button secondary" onClick={() => window.print()}><FileText size={16}/> Imprimir relatório</button></div></section>}
        {page === 'frequencia' && <><section className="panel"><PanelHeading icon={ChartNoAxesColumn} title="Frequência por turma" description="Resumo de participação nos encontros registrados."/><label className="field filter-field">Filtrar turma<select value={frequencyClass} onChange={(e) => setFrequencyClass(e.target.value)}><option value="all">Todas as turmas</option>{data.classes.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label></section><section className="panel">{data.students.filter((student) => frequencyClass === 'all' || data.classes.find((c) => c.id === frequencyClass)?.studentIds?.includes(student.id)).length ? <div className="table-wrap"><table><thead><tr><th>Participante</th><th>Turma</th><th>Encontros</th><th>Presenças</th><th>Frequência</th></tr></thead><tbody>{data.students.filter((student) => frequencyClass === 'all' || data.classes.find((c) => c.id === frequencyClass)?.studentIds?.includes(student.id)).map((student) => { const classGroup = data.classes.find((c) => c.studentIds?.includes(student.id)); const attendance = records.flatMap((record) => record.entries || []).filter((entry) => entry.studentId === student.id); const present = attendance.filter((entry) => entry.status === 'present').length; return <tr key={student.id}><td><b>{student.name}</b></td><td>{classGroup?.name || '—'}</td><td>{attendance.length}</td><td>{present}</td><td><span className="badge green">{attendance.length ? Math.round(present / attendance.length * 100) : 0}%</span></td></tr>; })}</tbody></table></div> : <Empty message="Sem dados de frequência" detail="Cadastre participantes e registre encontros para gerar o relatório."/>}</section></>}
        <footer className="page-footer">Campanha Evangelizadora <span>•</span> Gestão de encontros e participantes</footer>
      </div></main></div>
  </div>;
}

function PanelHeading({ icon: Icon, title, description }) { return <div className="panel-heading"><div className="panel-title-icon"><span className="heading-icon"><Icon size={18}/></span><div><h2>{title}</h2><p>{description}</p></div></div></div>; }
function Empty({ message, detail }) { return <div className="empty-state"><span className="empty-icon"><FileText size={20}/></span><b>{message}</b><p>{detail}</p></div>; }

createRoot(document.getElementById('root')).render(<App/>);
