import { Activity, Check, ChevronRight, ClipboardCheck, FileText, Plus } from 'lucide-react';

export default function OverviewPage({ data, stats, records, nav, reload, formatDate }) {
  return <>
    <section className="section-block"><div className="section-heading"><div><h2>Resumo da campanha</h2></div><button className="text-button" onClick={() => nav('relatorios')}>Ver relatórios <ChevronRight size={16}/></button></div><div className="stats-grid">{stats.map(({ label, value, icon: Icon, color }) => <article className="stat-card" key={label}><div className="stat-top"><span>{label}</span><span className={`stat-icon ${color}`}><Icon size={18}/></span></div><strong>{value}</strong></article>)}</div></section>
    <div className="quick-actions"><button className="button primary" onClick={() => nav('chamadas')}><Plus size={17}/> Registrar encontro</button><button className="button secondary" onClick={() => nav('turmas')}>Gerenciar turmas</button></div>
    <section className="panel"><div className="panel-heading"><div><h2>Atividade recente</h2><p>Últimos encontros registrados na campanha.</p></div><button className="icon-button muted" onClick={reload} aria-label="Atualizar encontros"><Activity size={17}/></button></div>{records.length ? <div className="record-list">{records.slice(0, 5).map((record) => <div className="record-row" key={record.id}><span className="record-symbol"><ClipboardCheck size={18}/></span><div className="record-info"><b>{data.classes.find((group) => group.id === record.classId)?.name || 'Encontro evangelizador'}</b><span>{record.lessonName || 'Encontro'} · {formatDate(record.date)}</span></div><span className="badge green"><Check size={12}/> {record.entries?.filter((entry) => entry.status === 'present').length || 0} presentes</span></div>)}</div> : <div className="empty-state"><span className="empty-icon"><FileText size={20}/></span><b>Nenhum encontro registrado ainda</b><p>Registre o primeiro encontro para ver a atividade recente aqui.</p><button className="button secondary" onClick={() => nav('chamadas')}>Registrar encontro</button></div>}</section>
  </>;
}
