import { Save, X } from 'lucide-react';
import { Modal } from './Modal';

function Heading({ id, title, description, onClose }) {
  return <div className="panel-heading"><div><h2 id={id}>{title}</h2><p>{description}</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Fechar"><X size={18}/></button></div>;
}
function Actions({ busy, label, onClose }) {
  return <div className="convert-modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button type="submit" className="button primary" disabled={busy}><Save size={16}/>{busy ? 'Salvando…' : label}</button></div>;
}

export function LessonContentDialog({ draft, setDraft, busy, error, onSave, onClose }) {
  return <Modal onClose={onClose}><section className="convert-modal scale-edit-modal" role="dialog" aria-modal="true" aria-labelledby="lesson-content-title"><Heading id="lesson-content-title" title="Conteúdo da lição" description={draft.title} onClose={onClose}/><form onSubmit={(event) => { event.preventDefault(); void onSave(); }}><label className="field scale-content-field">Anotações e conteúdo<textarea rows={9} maxLength={10000} value={draft.content} onChange={(event) => { const content = event.target.value; setDraft((current) => ({ ...current, content })); }} placeholder="Escreva aqui o conteúdo, tópicos ou anotações desta lição…"/><small>{draft.content.length}/10.000 caracteres</small></label>{error && <p role="alert">{error}</p>}<Actions busy={busy} label="Salvar conteúdo" onClose={onClose}/></form></section></Modal>;
}

export function ClassScaleDialog({ draft, setDraft, weekdays, nearestWeekday, busy, error, onSave, onClose }) {
  return <Modal onClose={onClose}><section className="convert-modal scale-edit-modal" role="dialog" aria-modal="true" aria-labelledby="class-start-title"><Heading id="class-start-title" title={`Escala da turma ${draft.name}`} description="Ao alterar o início, dia ou horário, a escala será ajustada para esta turma." onClose={onClose}/><form onSubmit={(event) => { event.preventDefault(); void onSave(); }}><div className="form-grid"><label className="field">Dia semanal<select value={draft.lessonWeekday} onChange={(event) => { const weekday = Number(event.target.value); setDraft((current) => ({ ...current, lessonWeekday: weekday, startDate: nearestWeekday(weekday, current.startDate) })); }}>{weekdays.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label><label className="field">Horário padrão<input type="time" value={draft.lessonTime || '09:00'} onChange={(event) => { const lessonTime = event.target.value; setDraft((current) => ({ ...current, lessonTime })); }} required/></label><label className="field">Data de início<input type="date" value={draft.startDate} onChange={(event) => { const startDate = event.target.value; setDraft((current) => ({ ...current, startDate })); }} required/></label></div>{error && <p role="alert">{error}</p>}<Actions busy={busy} label="Salvar e ajustar escala" onClose={onClose}/></form></section></Modal>;
}

export function LessonEditDialog({ draft, setDraft, teachers, lessons, defaultTime, busy, error, onSave, onClose }) {
  const update = (field, value) => setDraft((current) => ({ ...current, [field]: value }));
  return <Modal onClose={onClose}><section className="convert-modal scale-edit-modal" role="dialog" aria-modal="true" aria-labelledby="scale-edit-title"><Heading id="scale-edit-title" title="Editar aula" description="Altere a data, o tema, o professor ou o horário." onClose={onClose}/><form onSubmit={(event) => { event.preventDefault(); void onSave(); }}><div className="form-grid"><label className="field">Data da aula<input type="date" value={draft.date} onChange={(event) => update('date', event.target.value)} required/></label><label className="field">Horário da aula<input type="time" value={draft.timeOverride || draft.defaultTime || defaultTime} onChange={(event) => update('timeOverride', event.target.value === (draft.defaultTime || defaultTime) ? '' : event.target.value)} required/></label><label className="field">Título da aula<select value={draft.title} onChange={(event) => update('title', event.target.value)}>{lessons.map((lesson) => <option key={lesson}>{lesson}</option>)}{!lessons.includes(draft.title) && <option>{draft.title}</option>}</select></label><label className="field">Professor<select value={draft.teacherId} onChange={(event) => update('teacherId', event.target.value)}><option value="">A definir</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select></label></div><p>Horário padrão da turma: {draft.defaultTime || defaultTime}. Alterar aqui afeta somente esta aula.</p>{draft.date !== draft.originalDate && <label className="field scale-justification">Justificativa da mudança<textarea value={draft.justification || ''} onChange={(event) => update('justification', event.target.value)} required/></label>}{error && <p role="alert">{error}</p>}<Actions busy={busy} label="Salvar aula" onClose={onClose}/></form></section></Modal>;
}
